### ISSUE TITLE
does a subclass needs to be decorated?

### ISSUE THREAD

**Issue by vecernik** [NetanelBasal/ngx-take-until-destroy#1]
I have a (parent) class: 

@TakeUntilDestroy()
@Component({
  selector: 'msp-toolbar-command-button',
  templateUrl: './toolbar-command-button.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolbarCommandButtonComponent implements OnInit, OnDestroy {

  clicked$: Subject<any> = new Subject<any>()

  readonly destroyed$: Observable<boolean>

  ngOnInit() {
    this.clicked$
      .pipe(takeUntil(this.destroyed$))
      .subscribe((event: MouseEvent) => { ... })
  }
  ngOnDestroy() {
  }
}

works as a charm.

And another class as its subclass :
@Component({
  selector: 'msp-toolbar-line-command-button',
  templateUrl: '../toolbar-command-button/toolbar-command-button.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolbarLineCommandButtonComponent extends ToolbarCommandButtonComponent {
}

Does an inherited class needs to be decorated as well?

**Comment by kshaaban-** [comment]
I believe the extending class does **not** need to be decorated.

But you need to call the lifecycle methods of the super class if you override them.

In your example, if `ToolbarLineCommandButtonComponent` has its own implementation of `ngOnInit` and `ngOnDestroy`, they have to call the `super` ones

```ts
@Component({
  selector: 'msp-toolbar-line-command-button',
  templateUrl: '../toolbar-command-button/toolbar-command-button.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolbarLineCommandButtonComponent extends ToolbarCommandButtonComponent {

  ngOnInit() {
    super.ngOnInit();
    // carry on with the override
  }

  ngOnDestroy() {
    super.ngOnDestroy();
    // carry on with the override.
  }
}
```

**Comment by NetanelBasal** [comment]
As @kshaaban-  said 👆
