### ISSUE TITLE
RXJS v6 support

### ISSUE THREAD

**Issue by kmathy** [NetanelBasal/ngx-take-until-destroy#10]
Hi!

Just to let you know that the imports concerning rxjs (Observable, Subject,...) are not supported in the new version.

Can you create a release with the correct imports? 

`import { Observable, Subject } from 'rxjs';`

I would be interesting for those starting a new project and not wanting to install the rxjs-compat package. And I'm usually using your lib to manage unsubscriptions 😋 

Thanks in advance!! 👍

**Comment by kmathy** [comment]
Changes done, I've created a new branch containing this feature (feature/rxjs-6-support-new-imports), but I can't push them on git because no permission (error 403)

Once I have the rights, I'll retry to push 😃

**Comment by NetanelBasal** [comment]
You should fork the repo and create a pull request. https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by kmathy** [comment]
Yeah, found my mistake just after sending the comment, sorry ^^'

**Comment by NetanelBasal** [comment]
v3.0.0.
