### ISSUE TITLE
ngDestroy is now probably checked even without static code analysis

### ISSUE THREAD

**Issue by IlCallo** [NetanelBasal/ngx-take-until-destroy#12]
In Angular 6.1.0 changelog is reported this fix; https://github.com/angular/angular/commit/fc03427
Seems to me that this should remove the need of explicitly specifying an empty ngDestroy.
Can you check if this is the case?

**Comment by NetanelBasal** [comment]
It seems like it only applies to services, not components.

**Comment by IlCallo** [comment]
You're right, let's wait them to replicate also on components, ty anyway
