### ISSUE TITLE
why do you need decorator?

### ISSUE THREAD

**Issue by smnbbrv** [NetanelBasal/ngx-take-until-destroy#13]
This is funny, but I have a very similar library that was originated from the times of angular 2 beta.

https://github.com/smnbbrv/ngx-rx-collector

And even the name of the pipe that I am using there is the same :)

Just wondering: why do you need a decorator? This is literally waste of code.

**Comment by NetanelBasal** [comment]
> but I have a very similar library that was originated from the times of angular 2 beta

Doesn't make sense, pipeable operators haven't existed yet. 

> Just wondering: why do you need a decorator? This is literally waste of code.


It's from life before pipeable operators.
