### ISSUE TITLE
Missing @TakeUntilDestroy() and this.destroyed$ in version 4.0.0

### ISSUE THREAD

**Issue by vecernik** [NetanelBasal/ngx-take-until-destroy#14]
I really love this decorator. With version 3, I used `readonly destroyed$: Observable<boolean>` member passed to app logic-handling classes as an argument. Then takeUntil(destroyed$) took care of unsubscribing there. This way it's not necessary to pass the whole component to a method of other class.

In new version 4, @TakeUntilDestroy() and OnDestroy interface completely disappeared. Now passing the component class would make app-logic class dependent on a component type, which is not very handy. My point was to let a destroying component logic out of an app logic code as much as possible.

Would you consider to backport destroyed$ component observable into latest version, please? Perhaps as an another (optional) method for auto-unsubscribing.

**Comment by NetanelBasal** [comment]
I'm not sure what you mean. Can you give me a code example, please?

**Comment by vecernik** [comment]
This component and service works in version 3 (edited):

    // component
    import { OnDestroy, TakeUntilDestroy } from "ngx-take-until-destroy"

    @TakeUntilDestroy()
    @Component({
        selector: 'right-side'
    })
    export class RightSideComponent implements OnInit, OnDestroy {
        readonly destroyed$: Observable<boolean>

        constructor(private logicService: SuperLogicService) {}

        ngOnInit(): void {
            this.logicService.doSomethingUsefulUntil(this.destroyed$)
        }

        ngOnDestroy(): void { // leave even empty for aot
        }
    }

    // a shared app-logic service available to any component
    @Injectable()
    export class SuperLogicService {
        doSomethingUsefulUntil(destroyed$: Observable<any>): void {
            this.someIndependentStream$.pipe(
                takeUntil(destroyed$)
            )
            .subscribe(value => {
                // do something useful with value
            })
        }
    }

**Comment by NetanelBasal** [comment]
Added in 4.1.0.

**Comment by vecernik** [comment]
works like a charm, thank you.
