### ISSUE TITLE
not working before ngOnInit

### ISSUE THREAD

**Issue by sangecz** [NetanelBasal/ngx-take-until-destroy#16]
Hi,
I have an issue with this decorator on components. When it is used somewhere other than in ngOnInit or maybe before it, eg. constructor, the takeUntil under the hood does not work, subscription stays alive. This can be reproduced when you have eg. two routes and you switch between them.

Is this a known limitation? How can I prevent it? 

Interestingly, when I use subject on cmp class and completing it in `ngOnDestroy` and I use it in `takeUntil` anywhere within the class (cmp) it works, it unsubscribes the subscriptions as opposed to `untilDestroyed`. 

Thanks

**Comment by NetanelBasal** [comment]
Can you reproduce it in stackblitz, please?

**Comment by sangecz** [comment]
Yes, but could not find any angular 6 route example to extend

**Comment by NetanelBasal** [comment]
https://stackblitz.com/edit/angular-router-basic-example-uzuw3l?file=main.ts

**Comment by sangecz** [comment]
updated stackblitz https://stackblitz.com/edit/ngx-take-until
when a cmp is decorated with `@TakeUntilDestroy()` the `untilDestroyed` does not work.

I had another issue but only with my code that used custom decorator for translating container cmps by ngx-translate. The custom `@Translate` decorator had its own `_takeUntilDestroy$` prop and interfered with `untilDestroyed` op. 

Renaming prop in `@Translate` decorator and not using `@TakeUntilDestroy()` at all, using just `untilDestroyed`, seems to work.

**Comment by NetanelBasal** [comment]
You don't need the @TakeUntilDestroy() decorator anymore.

**Comment by NetanelBasal** [comment]
v5 dropped support for the `TakeUntilDestroy` decorator. Use only `untilDestroyed()`. Thanks.
