### ISSUE TITLE
Generates ERROR Error: object unsubscribed when used with ngx-auto-unsubscribe

### ISSUE THREAD

**Issue by damonachey** [NetanelBasal/ngx-take-until-destroy#19]
When this library is used with your other library in the same component it generates an error because ngx-auto-unsubscribe unsubs the __takeUntilDestroy subject before it is able to emit its item to terminate the subscription it's attached to.

See console here https://stackblitz.com/edit/angular-3e29em?file=src%2Fapp%2Fapp.component.html

**Comment by NetanelBasal** [comment]
Why using both?

**Comment by NetanelBasal** [comment]
Be consistent and use one library :)

**Comment by damonachey** [comment]
Thanks, the reason is that we have a lot of legacy code we don't want to touch that could take advantage of using both at the same time.  After more thought I think I would agree with you to only use one library at a time, and probably leave all the old code as is until we're ready to refactor it.

**Comment by NetanelBasal** [comment]
I'm not going to add this code as I think it's a rare case. Sorry and thanks.
