### ISSUE TITLE
Call decorated ngOnDestroy only one time

### ISSUE THREAD

**Issue by exsoflowe** [NetanelBasal/ngx-take-until-destroy#21]
I suggest it's better to add condition to check if componentInstance['__takeUntilDestroy'] already exists.
But also put function with next/complete inside condition.
Because now, for example, if we call untilDestroyed(this) 4 times we get next chain:

componentInstance.ngOnDestroy --> componentInstance.ngOnDestroy --> componentInstance.ngOnDestroy --> componentInstance.\_\_proto\_\_.ngOnDestroy

With this code
```
if (!componentInstance['__takeUntilDestroy']) {
  componentInstance['__takeUntilDestroy'] = new Subject();

  componentInstance[destroyMethodName] = function() {
    isFunction(originalDestroy) && originalDestroy.apply(this, arguments);
    componentInstance['__takeUntilDestroy'].next(true);
    componentInstance['__takeUntilDestroy'].complete();
  };
}
```
we **always** get something like
componentInstance.ngOnDestroy --> componentInstance.\_\_proto\_\_.ngOnDestroy

**Comment by NetanelBasal** [comment]
Nice catch! Thanks. Fixed in 5.2.0
