### ISSUE TITLE
Guaranteeing avoidance of parent class property name conflicts

### ISSUE THREAD

**Issue by nikkelma** [NetanelBasal/ngx-take-until-destroy#24]
Netanel, first thank you so much for all of your work.

When exploring similar `untilDestroyed` implementations, one solution used a `Symbol` as the property key to guarantee the avoidance of property name conflicts.

Does it make sense to switch from a bare string to a `Symbol` to guarantee `untilDestroyed` only works with (and detects) properties managed by itself? I know it's a fairly safe assumption that a component or class wouldn't have a `__takeUntilDestroy` property, yet I'm a fan of 100% guarantees - are there any side effects that would come with using a `Symbol`?

Thanks!

**Comment by NetanelBasal** [comment]
IE doesn't support symbols.
