### ISSUE TITLE
Feature Request - Implement type-safe of 'OnDestroy'

### ISSUE THREAD

**Issue by tumit** [NetanelBasal/ngx-take-until-destroy#25]
Please add type-safe of untilDestroyed or create new function something like 'untilComponentDestroyed' 

`export const untilComponentDestroyed = (componentInstance: OnDestroy) => untilDestroyed(componentInstance);`

it's nice to use type checking right ?

**Comment by j2L4e** [comment]
It's easily wrapped anyway:

```
import { OnDestroy } from '@angular/core';
import { untilDestroyed } from 'ngx-take-until-destroy';

export function takeUntilDestroy (component: OnDestroy) {
  return untilDestroyed(component);
}
```
