### ISSUE TITLE
Error with latest version (2.2.0)

### ISSUE THREAD

**Issue by catchshyam** [NetanelBasal/ngx-take-until-destroy#3]
Hello,

Big thumbs up for the plugin, thank you.

With the latest version, I get the following warning with "ng serve". I have not tested with AOT mode yet.

> WARNING in ./node_modules/ngx-take-until-destroy/dist/umd/take-until-destory.js
> 13:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
> 

On on app run, following error is thrown,

> take-until-destory.js:13 Uncaught Error: Cannot find module "."
>     at webpackMissingModule (take-until-destory.js:13)
>     at eval (take-until-destory.js:13)
>     at eval (take-until-destory.js:19)
>     at Object../node_modules/ngx-take-until-destroy/dist/umd/take-until-destory.js (vendor.bundle.js:2762)
> 

I am using RxJS version 5.5.6

Thanks.

**Comment by NetanelBasal** [comment]
Can you verify that it's happening only with the latest version, please?

**Comment by catchshyam** [comment]
With the latest release, the issue is reproducible only with the pipe operator. When used with the `this.destroyed` subject, no compilation warning are seen and application runs fine.

On my other project, I am using the version 1.1.2 (by the way, I don't see that release in the release history anymore) and no errors there.

**Comment by NetanelBasal** [comment]
I think I know what the problem is.

**Comment by NetanelBasal** [comment]
Try with 2.2.1, please.

**Comment by catchshyam** [comment]
Fixed!

You have been super responsive and helpful. Thank you

**Comment by kshaaban-** [comment]
Oops 😅
