### ISSUE TITLE
Adding pipe(untilDestroyed(this)) to all subscriptions made in our components makes some components to cause runtime errors.

### ISSUE THREAD

**Issue by ajaynarang** [NetanelBasal/ngx-take-until-destroy#31]
Similar to existing issue #23.

For some components it works fine but randomly it throws this exception, probably something to do with Angular page cycle which keeps ngOnDestroy readonly till initialization is over. Tried to debug but couldn't figure out the root problem.

Appreciate any help. Thanks

**Comment by NetanelBasal** [comment]
Can you reproduce it, please?

**Comment by NetanelBasal** [comment]
I am closing until reproducing.

**Comment by talamaska** [comment]
@NetanelBasal I do stumbled upon this as well. The pipe is generally working, but not when this property is read only.
