### ISSUE TITLE
Make it more universal

### ISSUE THREAD

**Issue by TheAifam5** [NetanelBasal/ngx-take-until-destroy#34]
Hey!
Since this project does not use any angular components, would be nice to make it more universal. I have plan use it in React. :)

Then we could rename to 'rxjs-take-until-destroy' .

Example:
```
this.settingsService
      .get('darkMode')
      .pipe(untilDestroyed<App>(this, 'componentWillUnmount'))
      .subscribe((p: boolean): void => this.setState({ darkMode: p }));
```

Regards,
TheAifam5

**Comment by NetanelBasal** [comment]
It's a bit annoying to repeat the hook name with every usage. Maybe we/you can export a react version, something like:

```ts
import { untilDestroyed as _untilDestroyed } from '';

export function untilDestroyed(component, name) {
  return _untilDestroyed(component, 'componentWillUnmount');
}
```

Regarding the package name, it's valid to change the name?

**Comment by TheAifam5** [comment]
@NetanelBasal
I mean, you can leave the hook name as is.
Hmm, the package name is like associated with Angular `ngx` but does not use any Angular components, but have Angular's dependencies which IMHO could be removed.

**Comment by NetanelBasal** [comment]
The Angular's dependencies are for dev only.

**Comment by TheAifam5** [comment]
oops, didn't seen that
