### ISSUE TITLE
Question about ngOnDestroy requirement

### ISSUE THREAD

**Issue by Maryannah** [NetanelBasal/ngx-take-until-destroy#35]
Hey there ! 

I had created the exact same operator for a projet I was hired on (before discovering your package), and we found out (the hard way) that you had to create at least the body of the `ngOnDestroy` method, even if it wasn't used.

I looked into it and it seemed to be an issue only in AOT compilation, but I've never really understood why. from a JS perspective only, creating the function in the decorator, even if it didn't exist, should not be an issue. Would you be able to explain it to me ? 

Thank you in advance, and keep up the good work ! (By the way, I'm in love with Akita !)

**Comment by NetanelBasal** [comment]
Hey, thanks. You can find the reason in the original thread. https://github.com/angular/angular/issues/16023#issuecomment-300680745

**Comment by chriszrc** [comment]
So, just checking, we do need this:

```
ngOnDestroy() {}
```

In our components still right? I don't see that requirement specified in the readme anymore?

**Comment by Maryannah** [comment]
No, you don't need it anymore @chriszrc !
