### ISSUE TITLE
Does it work also with base component ? 

### ISSUE THREAD

**Issue by RoyiNamir** [NetanelBasal/ngx-take-until-destroy#5]
I don't want to import this on each class. So I've created a base class .

Will it work  ( + AOT + Regular) if I declare this in a base class like this ? 

notice : decorator is at base and also ngOnDestroy : 

![image](https://user-images.githubusercontent.com/2842123/38088725-83f4929a-3365-11e8-95b9-575bf3e122ff.png)

**Comment by NetanelBasal** [comment]
Yes, it should work, you can check it. Add a log to your super method.
