### ISSUE TITLE
Question: How better remove subscriptions in component without recreate it?

### ISSUE THREAD

**Issue by Dok11** [NetanelBasal/ngx-take-until-destroy#6]
Look at my code:
```ts
@TakeUntilDestroy()
@Component({/* somу code */})
export class PageMessageComponent implements OnInit, OnDestroy {
	public ngOnInit(): void {
		this.loadData();

		this.translateService.onLangChange.subscribe(() => {
			// here I want remove subscriptions and in loadData create them again
			this.loadData();
		});
	}

	public ngOnDestroy(): void {
		this.appService.setPageCode('');
	}

	private loadData(): void {
		this.newsService.getItems()
			.pipe(untilDestroyed(this))
			.subscribe(news => {
				this.news = news;
				this.isLoaded = true;
			});
	}
```

My question is: how is best way to destroy all subscriptions in `onLangChange` and run them again? Because after language change I need load another data for current component.

Maybe I can run `this.ngOnDestroy();` - it's normal?

**Comment by Dok11** [comment]
Maybe this construction will be better:
How can I manually unsubscribe all subscription who marked as `.pipe(untilDestroyed(this))` operator?

**Comment by NetanelBasal** [comment]
You can't. This is the whole purpose of this library. It will unsubscribe only when the component destroyed.

**Comment by Dok11** [comment]
But if I will use `@TakeUntilDestroy('destroy')` and call this method anywhere in my logic then this will be works?

**Comment by NetanelBasal** [comment]
Closing.
