### ISSUE TITLE
This does not work rxjs@5.5.10

### ISSUE THREAD

**Issue by stevenrobijns** [NetanelBasal/ngx-take-until-destroy#8]
It does not work for me. Not with the pipable syntax and not without. I used rxjs 5.5.10.
I used the @TakeUntilDestroy() and had an empty OnDestroy method.

Actual subscription:

  constructor(private store: Store<fromAnnualWorks.State>) {
     this.store.pipe(
      takeUntil(this.destroyed$),
      select(fromDocs.getRequestBelcotaxResponse))
      .subscribe((res: RequestBelcotaxResponse) => {
        this.processBelcoTaxResponse(res);
      });
  }

**Comment by NetanelBasal** [comment]
can you reproduce with [stackblitz](https://stackblitz.com/)? It works in my application.

**Comment by stevenrobijns** [comment]
I'll see if I can find the time. Leaving this comment here though since i'm curious if anyone else is having the problem.

**Comment by stevenrobijns** [comment]
Do you have a stackblitz where it works?

**Comment by NetanelBasal** [comment]
Closing the issue. https://stackblitz.com/edit/ngx-take-until-destroy
